### ISSUE TITLE
Backup tools and resources missing

### ISSUE THREAD

**Issue by diegoaguilar** [ramnes/awesome-mongodb#12]
I've always wished to find nice and powerful backup operations tools for MongoDB, haven't you? It would be nice to get them listed here :)

**Comment by ramnes** [comment]
Well, most people use mongoexport/mongodump for that matter; do you have anything else in mind?

**Comment by jmayer13** [comment]
For migration and vm you can add https://github.com/eberhara/mongration

**Comment by ramnes** [comment]
Looks good @jmayer13, I'm going to add it right now. :+1: 

I'll close this for now, but please open a new PR/issue for each project you would like to see in awesome-mongodb.
