### ISSUE TITLE
I think we need more of tutorial links and books. Thanks for the list :)

### ISSUE THREAD

**Issue by vibhas777** [ramnes/awesome-mongodb#2]

**Comment by ramnes** [comment]
You're welcome!

I don't know any MongoDB book, and I feel like their documentation is already pretty extensive, hence the lack of tutorials. But if you know good learning resources, don't hesitate to open a new PR!

I'm closing that issue meanwhile, but I heard you. :+1:

**Comment by ramnes** [comment]
Also, I've just added a link to [MongoDB tutorials](https://docs.mongodb.org/manual/tutorial/) to the [https://github.com/ramnes/awesome-mongodb#documentation](Documentation) section.

**Comment by pearlberry** [comment]
Maybe you could include a section of tutorials for making apps that use Mongo? I know of a few good tutorials out there that use it and I'm sure there are a lot of them. (Like [this one](http://sahatyalkabov.com/create-a-tv-show-tracker-using-angularjs-nodejs-and-mongodb/), for example)

**Comment by ramnes** [comment]
@pealberry thanks again for #9; I added an other tutorial myself. :+1:

**Comment by pearlberry** [comment]
Sure, I'll add a couple more as well.
