### ISSUE TITLE
Do you accept articles written by Chinese?

### ISSUE THREAD

**Issue by zhaoyi0113** [ramnes/awesome-mongodb#43]
There are a few good articles about MongoDB written in Chinese, does this repo accept them?

**Comment by ramnes** [comment]
That's a good question! Let me think about it a bit and see if and how we can do this.

**Comment by ramnes** [comment]
I just opened https://github.com/sindresorhus/awesome/issues/1282, let see what comes out of this discussion!

**Comment by ramnes** [comment]
I'll close this until we have a consensus on the previously linked issue.
