### ISSUE TITLE
[suggestion] MongoDB for beginners

### ISSUE THREAD

**Issue by anto-christo** [ramnes/awesome-mongodb#69]
https://github.com/acm-dbit/mongodb-wkshop

Hi,
Recently we had a hands-on MongoDB workshop at our college. The trainer had created the above repo as a resource for the students, all of whom had no prior experience with MongoDB.

I personally find it very useful, particularly for someone who is new to Mongo. All the commands have been explained with examples and the repo also has some presentation explaining Mongo. There may be better resources available online. Still, I request you to go through the above repo and give your suggestion on whether it can be added to the list under Tutorials.

If yes, I'm ready to send a PR. Thank you.

**Comment by ramnes** [comment]
Hey @anto-christo,

The tutorial that your trainer made is very straightforward and indeed a good resource for someone that starts playing with MongoDB.

That being said, we already have multiple links listed for beginners and I feel that they are just as good; I'm mostly thinking of [the little MongoDB book](https://www.openmymind.net/2011/3/28/The-Little-MongoDB-Book/) and [this tutorial by Studio 3T](https://studio3t.com/knowledge-base/articles/mongodb-getting-started/).

So I'll close this, but thanks for opening this issue! If you come across other interesting resources in your courses, please share.

I'm pretty sure there was something very similar in the MongoDB documentation, with a reference dataset containing restaurants, but it seems gone with latest versions, which makes me sad. :disappointed:
